/* Generated By:JavaCC: Do not edit this line. ASTGen.java */
public class ASTGen implements ASTGenConstants {
        public static void main(String args[]) throws ParseException {
                new ASTGen(System.in);
                Class [] classes = Top();
                //Class.indent(new IndentOutput(System.out), 0, classes);
                Class.printJava(new JavaOutput(System.out), classes, null, false, null);

        }

//-- Define the grammatical rules of the input language: ---------------------
  static final public Class [] Top() throws ParseException {
                  Class [] classes; Args args;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 1:
    case 2:
      classes = Classes(0, null);
      break;
    default:
      jj_la1[0] = jj_gen;
                                     {if (true) return new Class[0];}
    }
    jj_consume_token(0);
                {if (true) return classes;}
    throw new Error("Missing return statement in function");
  }

  static final public Class [] Classes(int soFar, Args argList) throws ParseException {
                                             Class c; Class [] classes;
    //Class() | (Classes())*
            c = Class(argList);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 1:
    case 2:
      classes = Classes(soFar+1, argList);
      break;
    default:
      jj_la1[1] = jj_gen;
                                                classes = new Class[soFar+1];
    }
          classes[soFar] = c; {if (true) return classes;}
    throw new Error("Missing return statement in function");
  }

  static final public Class Class(Args argList) throws ParseException {
                             boolean isAbstract; String name; Class [] subclasses; Args args;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 1:
      jj_consume_token(1);
                     isAbstract = true;
      break;
    default:
      jj_la1[2] = jj_gen;
                                            isAbstract = false;
    }
    jj_consume_token(2);
    name = Id();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 3:
      jj_consume_token(3);
      args = ListArg(argList);
      jj_consume_token(4);
      break;
    default:
      jj_la1[3] = jj_gen;
                                          args = argList;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 5:
      jj_consume_token(5);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 1:
      case 2:
        subclasses = Classes(0, args);
        break;
      default:
        jj_la1[4] = jj_gen;
                                                subclasses = new Class[0];
      }
      jj_consume_token(6);
      break;
    default:
      jj_la1[5] = jj_gen;
            subclasses = new Class[0];
    }
                {if (true) return new Class(isAbstract, name, args, subclasses);}
    throw new Error("Missing return statement in function");
  }

  static final public Args ListArg(Args argList) throws ParseException {
                              Arg a;
    //Arg() Args()
            a = Arg();
                    argList = new Args(argList, a);
                {if (true) return Args(argList);}
    throw new Error("Missing return statement in function");
  }

  static final public Args Args(Args as) throws ParseException {
                      Args list; Arg after;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 7:
      jj_consume_token(7);
      after = Arg();
                            as = new Args(as, after); as=Args(as);
      break;
    default:
      jj_la1[6] = jj_gen;
                                                                       {if (true) return as;}
    }
                {if (true) return as;}
    throw new Error("Missing return statement in function");
  }

  static final public Arg Arg() throws ParseException {
             Token token; String vis, id; Type t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 8:
      token = jj_consume_token(8);
                           vis = token.image;
      break;
    case 9:
      token = jj_consume_token(9);
                               vis = token.image;
      break;
    case 10:
      token = jj_consume_token(10);
                             vis = token.image;
      break;
    default:
      jj_la1[7] = jj_gen;
           vis = null;
    }
    t = Type();
    id = Id();
                {if (true) return new Arg(vis, t, id);}
    throw new Error("Missing return statement in function");
  }

  static final public Type Type() throws ParseException {
               Type t; ArrayType arrayT;
    //NameType() ("[" "]")*
            t = NameType();
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case 11:
        ;
        break;
      default:
        jj_la1[8] = jj_gen;
        break label_1;
      }
      jj_consume_token(11);
      jj_consume_token(12);
                  t = new ArrayType(t);
    }
                {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

  static final public Type NameType() throws ParseException {
                   String [] str;
    //StringArray()
            str = StringArray(0);
                {if (true) return new NameType(str);}
    throw new Error("Missing return statement in function");
  }

  static final public String [] StringArray(int soFar) throws ParseException {
                                    String [] s; String str;
    //Id() ("." Id())*
            str = Id();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 13:
      jj_consume_token(13);
      s = StringArray(soFar+1);
      break;
    default:
      jj_la1[9] = jj_gen;
                                               s = new String[soFar + 1];
    }
                s[soFar] = str;
                {if (true) return s;}
    throw new Error("Missing return statement in function");
  }

  static final public String Id() throws ParseException {
               Token t;
    //IDENT
            t = jj_consume_token(IDENT);
                {if (true) return t.image;}
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public ASTGenTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[10];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x6,0x6,0x2,0x8,0x6,0x20,0x80,0x700,0x800,0x2000,};
   }

  /** Constructor with InputStream. */
  public ASTGen(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public ASTGen(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ASTGenTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public ASTGen(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ASTGenTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public ASTGen(ASTGenTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(ASTGenTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 10; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[23];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 10; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 23; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
